version: '3'
services:

    app:
        build: .
        command: >
                 bash -c "python manage.py makemigrations &&
                          python manage.py migrate &&
                          gunicorn --chdir /app sistema_escolar.wsgi:application --bind 0.0.0.0:8000"

        container_name: app
        ports:
            - 8000:8000
