# Generated by Django 3.0.8 on 2020-07-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0002_disciplina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
