# Generated by Django 3.0.8 on 2020-07-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0003_delete_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nota1', models.FloatField(verbose_name='Nota1')),
                ('nota2', models.FloatField(verbose_name='Nota2')),
                ('nota3', models.FloatField(verbose_name='Nota3')),
                ('nota4', models.FloatField(verbose_name='Nota4')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudantes.Estudante', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
    ]
